name: database_data_layer
description: Data layer for database operations
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  postgres: ^2.6.4 #^3.1.2 incompatible with migrant
  migrant: ^0.0.8
  migrant_db_postgresql: ^0.0.4
  migrant_source_fs: ^0.0.2
  # TODO remove later (used for old templating removal)
  sanitize_filename: ^1.0.5

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
