name: database_repository
description: Repository for database
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  path: ^1.8.2
  path_provider: ^2.1.3
  sanitize_filename: ^1.0.5
  charset_converter: ^2.2.0
  rxdart: ^0.27.7
  meta: ^1.10.0
  equatable: ^2.0.5
  database_data_layer:
    path: ../database_data_layer
  shared_kernel:
    path: ../shared_kernel

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
