name: progress_repository
description: A repository for managing ongoing progresses
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  rxdart: ^0.27.7
  equatable: ^2.0.5
  uuid: ^4.4.0
  progress_data_layer:
    path: ../progress_data_layer

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
