name: shared_kernel
description: A package containing functionality shared between packages.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  path: ^1.8.2

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
