name: settings_repository
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  meta: ^1.10.0
  equatable: ^2.0.5
  settings_data_layer:
    path: ../settings_data_layer

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
