name: files_repository
description: Library handling game_launcher filesystem operations like file copy and archiving
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  path: ^1.8.2
  win32_registry: ^1.1.2
  rxdart: ^0.27.7
  shared_kernel:
    path: ../shared_kernel

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
